tasks = [
    "PELVIS_TASK",
    "RIGHT_HAND_TASK",
    "LEFT_HAND_TASK",
    "HEAD_TASK",
    "T8_TASK",
    "RIGHT_UPPER_ARM_TASK",
    "RIGHT_FORE_ARM_TASK",
    "LEFT_UPPER_ARM_TASK",
    "LEFT_FORE_ARM_TASK",
    "RIGHT_UPPER_LEG_TASK",
    "RIGHT_LOWER_LEG_TASK",
    "LEFT_UPPER_LEG_TASK",
    "LEFT_LOWER_LEG_TASK",
    "RIGHT_TOE_TASK",
    "LEFT_TOE_TASK",
    "RIGHT_FOOT_TASK",
    "LEFT_FOOT_TASK",
    "JOINT_LIMITS_TASK",
    "JOINT_REG_TASK",
    "JOINT_VEL_LIMITS_TASK"
]

[IK]
verbosity = false
robot_velocity_variable_name = "robot_velocity"

[PELVIS_TASK]
type = "SE3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "Pelvis"
kp_linear = 20.0
kp_angular = 20.0
priority = 0
mask = [true, true, false]
weight = [10.0, 10.0, 10.0, 10.0, 10.0]

[RIGHT_HAND_TASK]
type = "SE3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "RightHand"
kp_linear = 20.0
kp_angular = 20.0
priority = 1
mask = [true, true, true]
weight = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
transformation_matrix = [-1.0, 0.0, 0.0, 0.0,
                        0.0, 0.0, 1.0, -0.02,
                        0.0, 1.0, 0.0, 0.05,
                        0.0, 0.0, 0.0, 1.0]

[LEFT_HAND_TASK]
type = "SE3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "LeftHand"
kp_linear = 20.0
kp_angular = 20.0
priority = 1
mask = [true, true, true]
weight = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
transformation_matrix = [1.0, 0.0, 0.0, 0.0,
                        0.0, 0.0, 1.0, -0.02,
                        0.0, -1.0, 0.0, 0.05,
                        0.0, 0.0, 0.0, 1.0]

[HEAD_TASK]
type = "SE3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "Head"
kp_linear = 20.0
kp_angular = 20.0
priority = 1
mask = [true, true, true]
weight = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
transformation_matrix = [0.0, -1.0,  0.0,  0.0,
                        0.0,  0.0,  1.0,  0.0,
                        -1.0,  0.0,  0.0,  0.1,
                        0.0,  0.0,  0.0,  1.0]

[T8_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "UpperTrunk"
kp_angular = 20.0
node_number = 6
weight = [1.0, 1.0, 1.0]
rotation_matrix = [0.0, 1.0, 0.0,
                   0.0, 0.0, 1.0,
                   1.0, 0.0, 0.0]

[RIGHT_UPPER_ARM_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "RightUpperArm"
kp_angular = 20.0
node_number = 7
weight = [1.0, 1.0, 1.0]
rotation_matrix = [1.0, 0.0, 0.0,
                   0.0, 0.0, 1.0,
                   0.0, -1.0, 0.0]

[RIGHT_FORE_ARM_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "RightForeArm"
kp_angular = 20.0
node_number = 8
weight = [1.0, 1.0, 1.0]
rotation_matrix = [1.0, 0.0, 0.0,
                   0.0, 0.0, 1.0,
                   0.0, -1.0, 0.0]

[LEFT_UPPER_ARM_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "LeftUpperArm"
kp_angular = 20.0
node_number = 5
weight = [1.0, 1.0, 1.0]
rotation_matrix = [1.0, 0.0, 0.0,
                   0.0, 0.0, -1.0,
                   0.0, 1.0, 0.0]

[LEFT_FORE_ARM_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "LeftForeArm"
kp_angular = 20.0
node_number = 4
weight = [1.0, 1.0, 1.0]
rotation_matrix = [1.0, 0.0, 0.0,
                   0.0, 0.0, -1.0,
                   0.0, 1.0, 0.0]

[RIGHT_UPPER_LEG_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "RightUpperLeg"
kp_angular = 20.0
node_number = 11
weight = [1.0, 1.0, 1.0]
rotation_matrix = [1.0, 0.0, 0.0,
                   0.0, 0.0, 1.0,
                   0.0, -1.0, 0.0]

[RIGHT_LOWER_LEG_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "RightLowerLeg"
kp_angular = 20.0
node_number = 12
weight = [1.0, 1.0, 1.0]
rotation_matrix = [1.0, 0.0, 0.0,
                   0.0, 0.0, 1.0,
                   0.0, -1.0, 0.0]

[LEFT_UPPER_LEG_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "LeftUpperLeg"
kp_angular = 20.0
node_number = 9
weight = [1.0, 1.0, 1.0]
rotation_matrix = [1.0, 0.0, 0.0,
                   0.0, 0.0, -1.0,
                   0.0, 1.0, 0.0]

[LEFT_LOWER_LEG_TASK]
type = "SO3Task"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "LeftLowerLeg"
kp_angular = 20.0
node_number = 10
weight = [1.0, 1.0, 1.0]
rotation_matrix = [1.0, 0.0, 0.0,
                   0.0, 0.0, -1.0,
                   0.0, 1.0, 0.0]


[RIGHT_FOOT_TASK]
type = "GravityTask"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
target_frame_name = "RightFoot"
kp = 20.0
node_number = 2
weight = [1.0, 1.0]
rotation_matrix = [0.0, 1.0, 0.0,
                  -1.0, 0.0, 0.0,
                   0.0, 0.0, 1.0]


[LEFT_FOOT_TASK]
type = "GravityTask"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
target_frame_name = "LeftFoot"
kp = 20.0
node_number = 1
weight = [1.0, 1.0]
rotation_matrix = [0.0, 1.0, 0.0,
                   -1.0, 0.0, 0.0,
                   0.0, 0.0, 1.0]

[RIGHT_TOE_TASK]
type = "FloorContactTask"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "RightToe"
kp_linear = 60.0
node_number = 2
mask = [true, true, true]
weight = [30.0, 30.0, 30.0]
vertical_force_threshold = 60.0

[LEFT_TOE_TASK]
type = "FloorContactTask"
robot_velocity_variable_name = "robot_velocity"
weight_provider_type = "ConstantWeightProvider"
frame_name = "LeftToe"
kp_linear = 60.0
node_number = 1
mask = [true, true, true]
weight = [30.0, 30.0, 30.0]
vertical_force_threshold = 60.0

[JOINT_LIMITS_TASK]
type = "JointConstraintTask"
robot_velocity_variable_name = "robot_velocity"
use_model_limits = false
sampling_time = 0.017
k_limits = 1.0
joints_list = ["jLeftKnee_rotz", "jRightKnee_rotz", "jLeftAnkle_rotz", "jRightAnkle_rotz", "jC7RightShoulder_rotx", "jC7LeftShoulder_rotx", "jT9T8_rotz", "jL5S1_roty", "jL5S1_rotx"]
upper_bounds = [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
lower_bounds = [-0.001, -0.001, -0.001, -0.001, -0.001, -0.001, 0.001, -0.001, 0.001]

[JOINT_REG_TASK]
type = "JointRegularizationTask"
weight_provider_type = "ConstantWeightProvider"
robot_velocity_variable_name = "robot_velocity"
weight = 0.000001


[JOINT_VEL_LIMITS_TASK]
type = "JointVelocityLimitsTask"
robot_velocity_variable_name = "robot_velocity"
upper_limit = 5.0
lower_limit = -5.0