joints_list = ['l_hip_pitch', 'l_hip_roll', 'l_hip_yaw', 'l_knee', 'l_ankle_pitch', 'l_ankle_roll',  # left leg
               'r_hip_pitch', 'r_hip_roll', 'r_hip_yaw', 'r_knee', 'r_ankle_pitch', 'r_ankle_roll',  # right leg
               'torso_pitch', 'torso_roll', 'torso_yaw',  # torso
               'neck_pitch', 'neck_roll', 'neck_yaw', # neck
               'l_shoulder_pitch', 'l_shoulder_roll', 'l_shoulder_yaw', 'l_elbow', # left arm
               'r_shoulder_pitch', 'r_shoulder_roll', 'r_shoulder_yaw', 'r_elbow'] # right arm

# for human model with mesh
human_joints_list = ['jLeftHip_rotx', 'jL5S1_rotx', 'jRightHip_rotx',
               'jLeftHip_roty', 'jL5S1_roty', 'jRightHip_roty', 'jLeftHip_rotz', 'jT9T8_rotx', 'jRightHip_rotz', 'jLeftKnee_roty', 'jT9T8_roty', 'jRightKnee_roty', 'jLeftKnee_rotz', 'jT9T8_rotz', 'jRightKnee_rotz', 'jLeftAnkle_rotx', 'jC7LeftShoulder_rotx', 'jT1C7_rotx', 'jC7RightShoulder_rotx', 'jRightAnkle_rotx', 'jLeftAnkle_roty', 'jLeftShoulder_rotx', 'jT1C7_roty', 'jRightShoulder_rotx', 'jRightAnkle_roty', 'jLeftAnkle_rotz', 'jLeftShoulder_roty', 'jT1C7_rotz', 'jRightShoulder_roty', 'jRightAnkle_rotz', 'jLeftBallFoot_roty', 'jLeftShoulder_rotz', 'jC1Head_rotx', 'jRightShoulder_rotz', 'jRightBallFoot_roty', 'jLeftElbow_roty', 'jC1Head_roty', 'jRightElbow_roty', 'jLeftElbow_rotz', 'jRightElbow_rotz', 'jLeftWrist_rotx', 'jRightWrist_rotx', 'jLeftWrist_rotz', 'jRightWrist_rotz']

# the joints are ordered as in the joints_list
# for model trained with shoulder/leg limits during retargeting
# initial_joints_configuration = [0.0036297440614715196, 0.029411764034607685, -0.012146692744945772, -0.0048554114872813095, 0.00409973896375526, -0.04229326696873599, # left leg
# 0.0003280223671510321, 0.029411765153663307, -0.012249749306457123, 0.0010131612332878901, 0.007286391880393088, -0.042258674686429014, # right leg
# -0.05000034750525513, 0.04999915197184974, -0.043485347491471815, #torso
# -0.0500000329604683, 0.04125879710832599, 0.024043276220421274, #neck
# 0.048304244207767154, 1.615931004002181, -0.037477399700386486, -0.01298800846269495, # left arm
# 0.03897236374766735, 1.5243838010732844, -0.04171736109521154, -0.030800414629153724]# right arm

# initial joint config hard coded if arms are down
initial_joints_configuration = [0.0, 0.0, 0.0,
                                0.0, 0.0, 0.0, # left leg
                                0.0, 0.0, 0.0,
                                0.0, 0.0, 0.0, # right leg
                                0.0, 0.0, 0.0, # torso
                                0.0, 0.0, 0.0, # neck
                                0.0, 0.0, 0.0, 0.0, # left arm
                                0.0, 0.0, 0.0, 0.0] # right arm

initial_base_height = 0.7748
# initial_base_quaternion =  [0.0, -0.0399893, 0.0, 0.9992001] # [x, y, z, w]
initial_base_quaternion = [0.0, 0.0, 0.0, 1.0]

root_link_frame_name = "root_link"
chest_link_frame_name = "chest"
left_foot_frame_name = "l_sole"
right_foot_frame_name = "r_sole"
sampling_time = 0.02
time_horizon = 0.8
slow_down_factor = 5.0
forward_direction = "x"
scaling_factor = 0.5
mocap_frame_rate = 50 # Hz
past_projected_base_horizon = 1.0
threshold_radius = 0.3
linear_pid_gain = 0.2
rotational_pid_gain = 2.0
trajectory_length = 500

[LEFT_FOOT]
number_of_corners = 4
corner_0  = [0.08, 0.03, 0.0]
corner_1  = [0.08, -0.03, 0.0]
corner_2  = [-0.08, -0.03, 0.0]
corner_3  = [-0.08, 0.03, 0.0]
on_threshold = 0.02
off_threshold = 0.02
switch_on_after = 0.04
switch_off_after = 0.04


[RIGHT_FOOT]
number_of_corners = 4
corner_0  = [0.08, 0.03, 0.0]
corner_1  = [0.08, -0.03, 0.0]
corner_2  = [-0.08, -0.03, 0.0]
corner_3  = [-0.08, 0.03, 0.0]
on_threshold = 0.02
off_threshold = 0.02
switch_on_after = 0.04
switch_off_after = 0.04

[MANN]
projected_base_datapoints = 12
onnx_model_path = "../datasets/trained_models/training_test_collab_no_pi_i_h_hb_no_bending_start_origin_subsampled_20241202-164937/training_test_collab_no_pi_i_h_hb_no_bending_start_origin_subsampled_20241202-164937_ep149.onnx"